baseurl = "/"
languageCode = "en-us"
title = "Kajembaran Rohmaniyyah"
description = "Pesantren Sirnarasa Cisirri, Ciomas, Panjalu, Ciamis - Jawa Barat, Indonesia. Kajembaran Rohmaniyyah."
image = "/og-image.jpg"